name: Build and upload nightly ipa

on:
  push:
    branches: [next]

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Get commit SHA
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Build
        run: xcodebuild -scheme Ferrite -configuration Release archive -archivePath build/Ferrite.xcarchive CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        env:
          IS_NIGHTLY: YES
      - name: Package ipa
        run: |
          mkdir Payload
          cp -r build/Ferrite.xcarchive/Products/Applications/Ferrite.app Payload
          zip -r Ferrite-iOS_nightly-${{ env.sha_short }}.ipa Payload
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Ferrite-iOS_nightly-${{ env.sha_short }}.ipa
          path: Ferrite-iOS_nightly-${{ env.sha_short }}.ipa
          if-no-files-found: error
